-   id: pyright
    name: pyright
    description: 'Python command line wrapper for pyright, a static type checker'
    entry: pyright
    language: python
    'types_or': [python, pyi]
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: '2.9.2'
